### ISSUE TITLE
paired-end sequencing data

### ISSUE THREAD

**Issue by SunJJ230120** [Comai-Lab/kmer-extract-by-trigger-site#1]
Hi, Comai-Lab

When I used kmer-extract-by-trigger-site.py to extracte kmers, how to input paired-end fasta of resequencing?

Best wishes!
Stephanie

**Comment by mericl** [comment]
Hi Stephanie, as this is cutting out kmers without retaining read information, the input fastq can be catted together R1 and R2 reads, or interleaved. It will take any standard fastq file / catted together fastqs, as it only reads the sequence line.

**Comment by SunJJ230120** [comment]
Thanks for your reply!
The paired-end sequence has a certain order. Is it necessary to reversely repeat the sequence of the second file and combine it with the sequence of the first file for analysis?
I have another question. When I get kmers from each individual, how to contrast count between male and female? python script or software?
Best wishes!
Stephanie

**Comment by mericl** [comment]
The reads can be interleaved or catted, as it is not tracking the reads order doesn't make any change to the output. Though once you have pulled all the kmers, you likely want to collapse canonical kmers if your data is not stranded. So if you had counts of AACC 5 and GGTT 3, you would then collapsed it into AACC 8, as with shotgun sequencing you don't know the orientation, so a AACC kmer is the same as a GGTT kmer. Though this is just an example, in reality your kmers would likely be at least 21bp long. After this the data can be combined and then compared with a custom script (python, Perl, R).

**Comment by SunJJ230120** [comment]
I see. thanks a lot.
Best,
Stephanie

**Comment by SunJJ230120** [comment]
Hi, Comai-Lab
I understand that the extraction of kmer has no relation with sequence direction. However, as in the article “A Y-chromosome–encoded small RNA acts as a sex determinant in persimmons”, we want to retrieve reads from paired-end data later. Does this sequence direction have a negative impact?
Best wishes!
Stephanie
